config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'games#index'
  get 'words/random', to: 'words#random'
  get 'games/cache', to: 'games#cache'
  resources :games
  resources :words
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/ongoing_game_validator.rb
# Prevents new associations with games that have finished

class OngoingGameValidator < ActiveModel::Validator
  def validate(record)
    record.errors.add(:game, "cannot be complete") unless record.game.ongoing?
  end
end

app/models/file_words_repository.rb
# frozen_string_literal: true

# Retrieve words from a \n de-limited file
class FileWordsRepository
  def initialize(file)
    @file = file
  end

  def random_word
    read_words
    max_index = @words.length
    random_index = rand(0..max_index - 1)
    get_word_at(random_index)
  end

  private

  def read_words
    @words = []
    while (line = @file.gets)
      @words.push(line.strip.to_s)
    end
    @file.close
    @words
  end

  def get_word_at(index)
    @words[index]
  end
end

app/models/game.rb
# frozen_string_literal: true

# Class representing a single Game
class Game < ApplicationRecord
  OBFUSCATION_CHARACTER = '*'

  has_many :turns, dependent: :delete_all
  validates :word, 
    presence: true,
    format: { with: /\A[a-z]*\z/, message: "only allows lower case letters" }
  validates :max_guesses, 
    presence: true,
    numericality: { only_integer: true, greater_than: 0 }

  def quantity_guesses_remaining
    max_guesses - wrong_letters.length
  end

  def obfuscated_word
    word.chars.map do |letter|
      right_letters.include?(letter) ? letter : nil
    end
  end

  def lost?
    quantity_guesses_remaining <= 0
  end

  def ongoing?
    lost? ? false : unguessed_letters? 
  end

  def won?
    !(ongoing? || lost?)
  end

  def wrong_letters
    turns.select { |guess| !guess.correct? }.map { |guess| guess.value }
  end

  private

  def right_letters
    turns.select { |guess| guess.correct? }.map { |guess| guess.value }
  end

  def unguessed_letters?
    obfuscated_word.include? nil
  end
end

app/models/turn.rb
class Turn < ApplicationRecord
  belongs_to :game

  validates :game, presence: true
  validates_with OngoingGameValidator
  validates :value,
    length: { is: 1 },
    uniqueness: { scope: :game_id, message: "Have already guessed %{value}" },
    format: { with: /\A[a-z]\z/, message: "only allows lower case" }

  def correct?
    game.word.include? value
  end
end
 

app/models/word.rb
class Word < ApplicationRecord
  validates :value, presence: { message: 'must not be empty' }
  validates :value, uniqueness: { message: 'can\'t use the same word twice'}
  validates :value, length: {
    in: 3..12,
    too_long: '%{count} characters is the maximum allowed',
    too_short: '%{count} characters is the minimum allowed'
  }
  validates :value, format: {
    with: /\A[a-z]+\z/,
    message: 'only allows lower case letters'
  }

  def self.random
    offset(rand(count)).first
  end
end

app/models/word_repository.rb
require 'http'

class WordRepository
  @@instance = nil

  def self.instance
    if !@@instance
      @@instance = WordRepository.new
    end
    @@instance
  end

  def request_word
    if cache.any?
      word = cache.pop
    else
      word = word_from_service
    end
    word
  end

  def fill_cache
    5.times do
      cache.push word_from_service
    end
    cache_size
  end

  def cache_size
    cache.count
  end

  private

  def cache
    @cache ||= []
  end

  def word_from_service
    res = HTTP.get('https://hangman-words-service.herokuapp.com/words/random').to_s
    word = JSON.parse res
    word['value'] || 'default'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
# frozen_string_literal: true

# Interfaces the game logic with the user
class GamesController < ApplicationController

  before_action :set_game, only: %i[update show destroy]

  def index
    @cached_count = "Cached #{WordRepository.instance.cache_size} results"
    @games = Game.all
    id = flash[:alternative_game_id]
    flash[:alternative_game] = id ? Game.find(id) : nil
  end

  def create
    begin
      word = WordRepository.instance.request_word
      game = Game.create(word: word, max_guesses: 5)
      redirect_to game_path game
    rescue StandardError => error
      flash[:notice] = error.message
      redirect_to games_path
    end
  end

  def show
    direct_to_alternative_game unless @game
  end

  def destroy
    if @game
      @game.destroy
      flash[:notice] = 'Deleted your game :('
    end
    redirect_to games_path
  end

  def cache
    WordRepository.instance.fill_cache
    redirect_to games_path
  end

  def update
    if @game
      guessed_letter = params['letter']
      turn = @game.turns.create(value: guessed_letter)
      flash[:notice] = turn.errors.full_messages[0] if turn.errors
      redirect_to game_path @game
    else
      direct_to_alternative_game
    end
  end

  private

  def direct_to_alternative_game
    flash[:alternative_game_id] = random_ongoing_game.id
    message = 'Problem running that game'
    flash[:notice] = message
    redirect_to games_path
  end

  def random_ongoing_game
    alternative_game = Game.all.sample until !Game.any? || (alternative_game && alternative_game.ongoing?)
    alternative_game
  end

  def set_game
    begin
      @game = Game.find(params[:id]) if params[:id]
    rescue
    end
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  def index
    @words = Word.all
  end

  def show
    @word = Word.find(params[:id])
  end

  def create
    word = Word.new(value: params[:word])
    if word.save
      flash[:notice] = "Created \"#{word.value}\""
    else
      flash[:notice] = "Had problems creating \"#{word.value}\" - #{word.errors.messages.first.second.first}"
    end

    redirect_to '/words'
  end

  def destroy
    word = Word.find(params[:id])
    word.destroy
    
    flash[:notice] = "Deleted \"#{word.value}\""
    redirect_to '/words'
  end

  def random
    render :json => Word.random
  end
end

app/helpers/alternative_game_link_helper.rb
module AlternativeGameLinkHelper
  def alternative_game_link(game, alternative)
    return unless game
    obfuscated = obfuscate game, alternative
    link_to "Try #{obfuscated} instead", (game_path game)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/guessed_letters_helper.rb
module GuessedLettersHelper
  def guessed_letters(game)
    "{ #{game.wrong_letters.join(', ')} }"
  end
end

app/helpers/obfuscation_helper.rb
module ObfuscationHelper
  def obfuscate(game, replacement) 
    game.obfuscated_word.map{ |letter| (letter || replacement) }.join
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/games/index.html.erb
<div id="overview">
  <h1>Hangman games</h1>
</div>

<div class="menu">
<%= render 'shared/new_game' %>
<%= link_to 'Google', 'http://google.com' %>
<%= link_to 'Fill the cache', games_cache_url %>
</div>

<div id="content">
  <div id="main">
    <p class="notice"><%= flash[:notice] %></p>
    <p class="alternative_game"><%= alternative_game_link(flash[:alternative_game], '*') %></p>
    <table>
      <% @games.each do |game| %>
        <tr>
          <td><%= "##{game.id}"%>
          <td>"<%= obfuscate(game, '*') %>"</td>
          <td><%= game.quantity_guesses_remaining %></td>
          <td><%= link_to (game.ongoing? ? 'Play' : 'Review'), game_path(game) %></td>
          <td><%= link_to 'Delete', game_path(game), method: :delete %></td>
        </tr>
      <% end %>
    </table>
  </div>
</div>
<p class="status"><%= @cached_count %></p>

app/views/games/show.html.erb
<div id="overview">
  <h1>You are trying to guess <%= obfuscate(@game, '*') %></h1>
</div>

<div class="menu"><%= link_to 'Your games', games_path %></div>

<div id="content">
  <div id="main">
    <p id="notice"><%= notice %></p>
    <p>You have <%= @game.quantity_guesses_remaining %> lives remaining
    <p>You have used <%= guessed_letters @game %>

    <% if @game.ongoing? %>
      <%= form_tag(game_path @game, method: "post") do %>
        <input name="_method" type="hidden" value="patch" />
        <%= label_tag(:letter, "Letter:") %>
        <%= text_field_tag(:letter) %>
        <%= submit_tag("Guess") %>
      <% end %>
    <% elsif @game.won? %>
      <div id='win_message' >
      Well done, you've won! :D
      <div class="button page-action"><%= render 'shared/new_game' %></div>
      </div>
    <% elsif @game.lost? %>
      <div id='lose_message'>
      Ooops, you lost :( The word was <%= @game.word %>
      <div class="button"><%= render 'shared/new_game' %></div>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyRailsHangman</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_new_game.html.erb
<%= link_to 'Start a new game', games_path, method: :post %>

app/views/words/index.html.erb
<h1>Add a word!</h1>

<%= form_tag("/words", method: "post") do %>
  <%= label_tag(:word, "Word:") %>
  <%= text_field_tag(:word) %>
  <%= submit_tag("Add word") %>
<% end %>

<p id="notice"><%= notice %></p>

<h1>I know about the words:</h1>

<table>
  <% @words.each do |word| %>
    <tr>
      <td>"<%= word.value %>"</td>
      <td><%= word.created_at %></td>
      <td><%= link_to 'Show', word_path(word) %></td>
      <td><%= link_to "Delete", word_path(word), method: :delete %></td>
    </tr>
  <% end %>
</table>

app/views/words/show.html.erb
"<%= @word.value %>" added at <%= @word.created_at %>